const image = JSON.stringify({image_intro: 'teste'});

const mockData = {
  items: [
    {
      data_publicacao: '20/09/2023',
      destaque: true,
      editoriais: 'ibge',
      id: 1,
      imagens: image,
      introducao: 'Introdução da primeira notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Notícia',
      titulo: 'Titulo da primeira notícia',
    },
    {
      data_publicacao: '19/09/2023',
      destaque: true,
      editoriais: 'ibge',
      id: 2,
      imagens: image,
      introducao: 'Introdução da segunda notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Release',
      titulo: 'Titulo da segunda notícia',
    },
    {
      data_publicacao: '18/09/2023',
      destaque: false,
      editoriais: 'ibge',
      id: 3,
      imagens: image,
      introducao: 'Introdução da terceira notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Notícia',
      titulo: 'Titulo da terceira notícia',
    },
    {
      data_publicacao: '17/09/2023',
      destaque: false,
      editoriais: 'ibge',
      id: 4,
      imagens: image,
      introducao: 'Introdução da quarta notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Release',
      titulo: 'Titulo da quarta notícia',
    },
    {
      data_publicacao: '19/09/2023',
      destaque: true,
      editoriais: 'ibge',
      id: 2,
      imagens: image,
      introducao: 'Introdução da quinta notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Release',
      titulo: 'Titulo da quinta notícia',
    },
    {
      data_publicacao: '18/09/2023',
      destaque: false,
      editoriais: 'ibge',
      id: 3,
      imagens: image,
      introducao: 'Introdução da sexta notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Notícia',
      titulo: 'Titulo da sexta notícia',
    },
    {
      data_publicacao: '19/09/2023',
      destaque: true,
      editoriais: 'ibge',
      id: 2,
      imagens: image,
      introducao: 'Introdução da setima notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Release',
      titulo: 'Titulo da setima notícia',
    },
    {
      data_publicacao: '18/09/2023',
      destaque: false,
      editoriais: 'ibge',
      id: 3,
      imagens: image,
      introducao: 'Introdução da oitava notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Notícia',
      titulo: 'Titulo da oitava notícia',
    },
    {
      data_publicacao: '19/09/2023',
      destaque: true,
      editoriais: 'ibge',
      id: 2,
      imagens: image,
      introducao: 'Introdução da nona notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Release',
      titulo: 'Titulo da nona notícia',
    },
    {
      data_publicacao: '18/09/2023',
      destaque: false,
      editoriais: 'ibge',
      id: 3,
      imagens: image,
      introducao: 'Introdução da decima notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Notícia',
      titulo: 'Titulo da decima notícia',
    },
    {
      data_publicacao: '19/09/2023',
      destaque: true,
      editoriais: 'ibge',
      id: 2,
      imagens: image,
      introducao: 'Introdução da decima primeira notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Release',
      titulo: 'Titulo da decima primeira notícia',
    },
    {
      data_publicacao: '18/09/2023',
      destaque: false,
      editoriais: 'ibge',
      id: 3,
      imagens: image,
      introducao: 'Introdução da decima segunda notícia',
      link: 'google.com',
      produto_id: 0,
      produtos: '',
      produtos_relacionados: '',
      tipo: 'Notícia',
      titulo: 'Titulo da decima segunda notícia',
    },]
  };

  // const mockData = [
  //   {
  //     data_publicacao: '20/09/2023',
  //     destaque: true,
  //     editoriais: 'ibge',
  //     id: 1,
  //     imagens: {"image_intro":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""},
  //     introducao: 'Introdução da primeira notícia',
  //     link: 'google.com',
  //     produto_id: 0,
  //     produtos: '',
  //     produtos_relacionados: '',
  //     tipo: 'Notícia',
  //     titulo: 'Titulo da primeira notícia',
  //   },
  //   {
  //     data_publicacao: '19/09/2023',
  //     destaque: true,
  //     editoriais: 'ibge',
  //     id: 2,
  //     imagens: {"image_intro":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""},
  //     introducao: 'Introdução da segunda notícia',
  //     link: 'google.com',
  //     produto_id: 0,
  //     produtos: '',
  //     produtos_relacionados: '',
  //     tipo: 'Release',
  //     titulo: 'Titulo da segunda notícia',
  //   },
  //   {
  //     data_publicacao: '18/09/2023',
  //     destaque: false,
  //     editoriais: 'ibge',
  //     id: 3,
  //     imagens: {"image_intro":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""},
  //     introducao: 'Introdução da terceira notícia',
  //     link: 'google.com',
  //     produto_id: 0,
  //     produtos: '',
  //     produtos_relacionados: '',
  //     tipo: 'Notícia',
  //     titulo: 'Titulo da terceira notícia',
  //   },
  //   {
  //     data_publicacao: '17/09/2023',
  //     destaque: false,
  //     editoriais: 'ibge',
  //     id: 4,
  //     imagens: {"image_intro":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_THUMB.jpg","float_intro":"","image_intro_alt":"","image_intro_caption":"","image_fulltext":"images\/agenciadenoticias\/ibge\/2023_09\/Doaes_HOME.jpg","float_fulltext":"","image_fulltext_alt":"","image_fulltext_caption":""},
  //     introducao: 'Introdução da quarta notícia',
  //     link: 'google.com',
  //     produto_id: 0,
  //     produtos: '',
  //     produtos_relacionados: '',
  //     tipo: 'Release',
  //     titulo: 'Titulo da quarta notícia',
  //   }
  // ]

  export default mockData;
  
